#!/bin/bash

sed -i -e 's/#level/level/g' /etc/NetworkManager/NetworkManager.conf

echo -e "DEVICE=eth0 \
NM_CONTROLLED=yes \
ONBOOT=yes" > /etc/sysconfig/network-scripts/ifcfg-eth0

echo "NETWORKING=yes" > /etc/sysconfig/network
