#!/bin/bash

sed -i -e 's/#level/level/g' /etc/NetworkManager/NetworkManager.conf

echo -e "DEVICE=eth0 \
NM_CONTROLLED=yes \
ONBOOT=yes" > /etc/sysconfig/network-scripts/ifcfg-eth0

echo "NETWORKING=yes" > /etc/sysconfig/network

echo -e "net.ipv6.conf.all.disable_ipv6=1 \
net.ipv6.conf.default.disable_ipv6=1" > /etc/sysctl.d/90-no-ipv6

/sbin/sysctl -w net.ipv6.conf.all.disable_ipv6=1
/sbin/sysctl -w net.ipv6.conf.default.disable_ipv6=1
