#!/bin/bash

# rm /etc/sysconfig/network || echo "cant remove syconfig/network"
#rm -rf /etc/systemd/system/NetworkManager-wait-online.service.d/ || echo "cant remove magic override"
rm -f /usr/sbin/ifup-local || echo "cant remove ifup-local"

